### ISSUE TITLE
setup baseline test with included git directory

### ISSUE THREAD

**Issue by goatfryed** [goatfryed/git-notify#11]
Our baseline integration tests need to verify whether the core properly integrates with git.
For this, we want to run the tests in against a valid git test directory & worktree and manage this setup in our repository itself.

Setup a baseline test on a test dir containing a git repository managed by this repository.

[It doesn't seem trivial, nor complicated.](https://stackoverflow.com/questions/6839781/what-happens-when-you-run-git-add-git-in-a-git-repository)

**Comment by PhilGarb** [comment]
Hallo
